version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:6

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache
      - run:
          name: Install empty placeholders
          command: |
            echo "export default {};" > piwik.js
            echo "export default { u: 'something' };" > mailchimp.js
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-cache
          paths:
            - ~/.npm
      - run:
          name: Build site
          command: npm run build-production
      - run:
          name: Run test
          command: npm run ci-with-server
